# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieSearchApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieSearchApp
  pod 'SnapKit', '5.6.0'
  pod 'Then', '~> 3.0.0'

  target 'MovieSearchAppTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
  end

end
